# Generated by Django 4.0.1 on 2022-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('T-25', 'T-25'), ('T-6', 'T-6'), ('FT Flume', 'FT Flume'), ('Box Drain', 'Box Drain')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='category',
            field=models.CharField(blank=True, choices=[('T-25', 'T-25'), ('T-6', 'T-6'), ('FT Flume', 'FT Flume'), ('Box Drain', 'Box Drain')], max_length=50, null=True),
        ),
    ]
